export const primitiveColors = {
  gray: [
    { scale: '50', value: '#F9FAFB' },
    { scale: '100', value: '#F3F4F6' },
    { scale: '200', value: '#E5E7EB' },
    { scale: '300', value: '#D1D5DB' },
    { scale: '400', value: '#9CA3AF' },
    { scale: '500', value: '#6B7280' },
    { scale: '600', value: '#4B5563' },
    { scale: '700', value: '#374151' },
    { scale: '800', value: '#1F2937' },
    { scale: '900', value: '#111827' },
  ],
  blue: [
    { scale: '50', value: '#EFF6FF' },
    { scale: '100', value: '#DBEAFE' },
    { scale: '200', value: '#BFDBFE' },
    { scale: '300', value: '#93C5FD' },
    { scale: '400', value: '#60A5FA' },
    { scale: '500', value: '#3B82F6' },
    { scale: '600', value: '#2563EB' },
    { scale: '700', value: '#1D4ED8' },
    { scale: '800', value: '#1E40AF' },
    { scale: '900', value: '#1E3A8A' },
  ],
  red: [
    { scale: '50', value: '#FEF2F2' },
    { scale: '100', value: '#FEE2E2' },
    { scale: '200', value: '#FECACA' },
    { scale: '300', value: '#FCA5A5' },
    { scale: '400', value: '#F87171' },
    { scale: '500', value: '#EF4444' },
    { scale: '600', value: '#DC2626' },
    { scale: '700', value: '#B91C1C' },
    { scale: '800', value: '#991B1B' },
    { scale: '900', value: '#7F1D1D' },
  ],
  green: [
    { scale: '50', value: '#F0FDF4' },
    { scale: '100', value: '#DCFCE7' },
    { scale: '200', value: '#BBF7D0' },
    { scale: '300', value: '#86EFAC' },
    { scale: '400', value: '#4ADE80' },
    { scale: '500', value: '#22C55E' },
    { scale: '600', value: '#16A34A' },
    { scale: '700', value: '#15803D' },
    { scale: '800', value: '#166534' },
    { scale: '900', value: '#14532D' },
  ],
  yellow: [
    { scale: '50', value: '#FEFCE8' },
    { scale: '100', value: '#FEF9C3' },
    { scale: '200', value: '#FEF08A' },
    { scale: '300', value: '#FDE047' },
    { scale: '400', value: '#FACC15' },
    { scale: '500', value: '#EAB308' },
    { scale: '600', value: '#CA8A04' },
    { scale: '700', value: '#A16207' },
    { scale: '800', value: '#854D0E' },
    { scale: '900', value: '#713F12' },
  ],
};

export const semanticColors = [
  { name: 'Background Primary', token: 'color.background.primary', value: '#FFFFFF' },
  { name: 'Background Secondary', token: 'color.background.secondary', value: '#F9FAFB' },
  { name: 'Background Tertiary', token: 'color.background.tertiary', value: '#F3F4F6' },
  { name: 'Text Primary', token: 'color.text.primary', value: '#111827' },
  { name: 'Text Secondary', token: 'color.text.secondary', value: '#4B5563' },
  { name: 'Text Tertiary', token: 'color.text.tertiary', value: '#9CA3AF' },
  { name: 'Interactive Primary', token: 'color.interactive.primary', value: '#2563EB' },
  { name: 'Interactive Secondary', token: 'color.interactive.secondary', value: '#4B5563' },
  { name: 'Border Default', token: 'color.border.default', value: '#E5E7EB' },
  { name: 'Border Strong', token: 'color.border.strong', value: '#D1D5DB' },
  { name: 'Status Success', token: 'color.status.success', value: '#16A34A' },
  { name: 'Status Warning', token: 'color.status.warning', value: '#CA8A04' },
  { name: 'Status Danger', token: 'color.status.danger', value: '#DC2626' },
  { name: 'Status Info', token: 'color.status.info', value: '#2563EB' },
];

export const typographyScale = [
  { name: 'Heading XL', token: 'heading-xl', fontSize: 36, lineHeight: 40, weight: '700' },
  { name: 'Heading LG', token: 'heading-lg', fontSize: 30, lineHeight: 36, weight: '700' },
  { name: 'Heading MD', token: 'heading-md', fontSize: 24, lineHeight: 32, weight: '600' },
  { name: 'Heading SM', token: 'heading-sm', fontSize: 20, lineHeight: 28, weight: '600' },
  { name: 'Body LG', token: 'body-lg', fontSize: 18, lineHeight: 28, weight: '400' },
  { name: 'Body MD', token: 'body-md', fontSize: 16, lineHeight: 24, weight: '400' },
  { name: 'Body SM', token: 'body-sm', fontSize: 14, lineHeight: 20, weight: '400' },
  { name: 'Label LG', token: 'label-lg', fontSize: 16, lineHeight: 24, weight: '500' },
  { name: 'Label MD', token: 'label-md', fontSize: 14, lineHeight: 20, weight: '500' },
  { name: 'Label SM', token: 'label-sm', fontSize: 12, lineHeight: 16, weight: '500' },
  { name: 'Caption', token: 'caption', fontSize: 12, lineHeight: 16, weight: '400' },
];

export const spacingScale = [
  { token: 'spacing.0', value: 0 },
  { token: 'spacing.1', value: 1 },
  { token: 'spacing.2', value: 2 },
  { token: 'spacing.3', value: 3 },
  { token: 'spacing.4', value: 4 },
  { token: 'spacing.5', value: 5 },
  { token: 'spacing.6', value: 6 },
  { token: 'spacing.8', value: 8 },
  { token: 'spacing.10', value: 10 },
  { token: 'spacing.12', value: 12 },
  { token: 'spacing.16', value: 16 },
  { token: 'spacing.20', value: 20 },
  { token: 'spacing.24', value: 24 },
  { token: 'spacing.32', value: 32 },
  { token: 'spacing.40', value: 40 },
];

export const radiusScale = [
  { token: 'radius.none', value: 0 },
  { token: 'radius.xs', value: 2 },
  { token: 'radius.sm', value: 4 },
  { token: 'radius.md', value: 8 },
  { token: 'radius.lg', value: 12 },
  { token: 'radius.xl', value: 16 },
  { token: 'radius.2xl', value: 24 },
  { token: 'radius.full', value: 9999 },
];

export const componentsList = [
  { name: 'Box', category: 'primitives', description: 'Basic layout container wrapping View.' },
  { name: 'Text', category: 'primitives', description: 'Typography component with variant-based styling.' },
  { name: 'Pressable', category: 'primitives', description: 'Touch-interactive wrapper with haptic feedback.' },
  { name: 'Stack', category: 'primitives', description: 'Flex layout with direction, gap, alignment.' },
  { name: 'Button', category: 'inputs', description: 'Primary action trigger with variants and sizes.' },
  { name: 'TextInput', category: 'inputs', description: 'Text field with label, error, and helper text.' },
  { name: 'Checkbox', category: 'inputs', description: 'Binary toggle with label support.' },
  { name: 'Switch', category: 'inputs', description: 'Toggle switch for on/off settings.' },
  { name: 'IconButton', category: 'inputs', description: 'Icon-only button with filled/outlined/ghost variants.' },
  { name: 'RadioGroup', category: 'inputs', description: 'Single-select option group.' },
  { name: 'Avatar', category: 'display', description: 'User avatar with image or initials fallback.' },
  { name: 'Badge', category: 'display', description: 'Status indicator with semantic variants.' },
  { name: 'Card', category: 'display', description: 'Content container with optional press action.' },
  { name: 'Tag', category: 'display', description: 'Categorization label with closable option.' },
  { name: 'Toast', category: 'feedback', description: 'Temporary notification with auto-dismiss.' },
  { name: 'Dialog', category: 'feedback', description: 'Modal dialog with title, message, and actions.' },
  { name: 'BottomSheet', category: 'feedback', description: 'Bottom slide-up panel with handle.' },
  { name: 'Snackbar', category: 'feedback', description: 'Brief feedback bar with optional action.' },
  { name: 'Divider', category: 'layout', description: 'Visual separator line.' },
  { name: 'Spacer', category: 'layout', description: 'Empty space with fixed size.' },
  { name: 'SafeArea', category: 'layout', description: 'Safe area insets wrapper.' },
  { name: 'Header', category: 'navigation', description: 'Top navigation bar with title and actions.' },
  { name: 'TabBar', category: 'navigation', description: 'Bottom tab navigation with badges.' },
  { name: 'NavigationBar', category: 'navigation', description: 'iOS-style navigation bar with large title.' },
];
