import * as fs from 'fs';
import * as path from 'path';

interface TokenValue {
  value: unknown;
}

interface TokenGroup {
  [key: string]: TokenValue | TokenGroup;
}

function readJsonFile(filePath: string): TokenGroup {
  const content = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(content);
}

function getAllJsonFiles(dir: string): string[] {
  const files: string[] = [];
  if (!fs.existsSync(dir)) return files;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getAllJsonFiles(fullPath));
    } else if (entry.name.endsWith('.json')) {
      files.push(fullPath);
    }
  }
  return files;
}

function deepMerge(target: TokenGroup, source: TokenGroup): TokenGroup {
  for (const key of Object.keys(source)) {
    if (
      source[key] &&
      typeof source[key] === 'object' &&
      !('value' in source[key]) &&
      target[key] &&
      typeof target[key] === 'object' &&
      !('value' in target[key])
    ) {
      target[key] = deepMerge(target[key] as TokenGroup, source[key] as TokenGroup);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

function resolveReference(value: string, allTokens: TokenGroup): unknown {
  if (typeof value !== 'string' || !value.startsWith('{') || !value.endsWith('}')) {
    return value;
  }
  const refPath = value.slice(1, -1).split('.');
  let current: unknown = allTokens;
  for (const segment of refPath) {
    if (current && typeof current === 'object' && segment in (current as Record<string, unknown>)) {
      current = (current as Record<string, unknown>)[segment];
    } else {
      return value;
    }
  }
  if (current && typeof current === 'object' && 'value' in (current as Record<string, unknown>)) {
    return (current as Record<string, unknown>).value;
  }
  return current;
}

function resolveTokens(tokens: TokenGroup, allTokens: TokenGroup): TokenGroup {
  const resolved: TokenGroup = {};
  for (const key of Object.keys(tokens)) {
    const token = tokens[key];
    if (token && typeof token === 'object' && 'value' in token) {
      const value = (token as TokenValue).value;
      if (typeof value === 'string') {
        resolved[key] = { value: resolveReference(value, allTokens) };
      } else {
        resolved[key] = token;
      }
    } else if (token && typeof token === 'object') {
      resolved[key] = resolveTokens(token as TokenGroup, allTokens);
    }
  }
  return resolved;
}

function flattenValues(tokens: TokenGroup): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const key of Object.keys(tokens)) {
    const token = tokens[key];
    if (token && typeof token === 'object' && 'value' in token) {
      result[key] = (token as TokenValue).value;
    } else if (token && typeof token === 'object') {
      result[key] = flattenValues(token as TokenGroup);
    }
  }
  return result;
}

function main() {
  const srcDir = path.resolve(__dirname, '../src');
  const outputDir = path.resolve(__dirname, '../output');

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Resolve tokens per-tier in order: primitive → semantic → component
  // Each tier resolves against the already-resolved tokens from previous tiers,
  // ensuring chained references (component → semantic → primitive) resolve fully.
  const tiers = ['primitive', 'semantic', 'component'];
  let resolvedTokens: TokenGroup = {};

  for (const tier of tiers) {
    const tierDir = path.join(srcDir, tier);
    const files = getAllJsonFiles(tierDir);

    let tierTokens: TokenGroup = {};
    for (const file of files) {
      const data = readJsonFile(file);
      tierTokens = deepMerge(tierTokens, data);
    }

    // Merge raw tier tokens into the resolved pool for lookup
    const lookupTokens = deepMerge({ ...resolvedTokens }, tierTokens);
    // Resolve this tier's references against the pool (previous tiers are already resolved)
    const resolvedTier = resolveTokens(tierTokens, lookupTokens);
    // Merge resolved tier into the cumulative resolved tokens
    resolvedTokens = deepMerge(resolvedTokens, resolvedTier);
  }

  const flattened = flattenValues(resolvedTokens);

  // Write JSON output
  fs.writeFileSync(
    path.join(outputDir, 'tokens.json'),
    JSON.stringify(flattened, null, 2),
  );

  // Write TypeScript output
  const tsContent = `// Auto-generated by @zzem-design-system/tokens build
// Do not edit manually

export const tokens = ${JSON.stringify(flattened, null, 2)} as const;

export type Tokens = typeof tokens;
`;
  fs.writeFileSync(path.join(outputDir, 'tokens.ts'), tsContent);

  console.log('Tokens built successfully!');
  console.log(`  → output/tokens.json`);
  console.log(`  → output/tokens.ts`);
}

main();
